# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Anki synchronization server installation tasks
  block:
    - name: Validate Anki synchronization server configuration
      when: anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Anki synchronization server
      when: anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-anki
    - install-all
    - install-anki

- name: Perform Anki synchronization server uninstallation tasks
  block:
    - name: Uninstall Anki synchronization server
      when: not anki_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-anki
