# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Anki synchronization server installation tasks
  when: anki_enabled | bool
  tags:
    - setup-all
    - setup-anki
    - install-all
    - install-anki
  block:
    - name: Validate Anki synchronization server configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Anki synchronization server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Anki synchronization server uninstallation tasks
  when: not anki_enabled | bool
  tags:
    - setup-all
    - setup-anki
  block:
    - name: Uninstall Anki synchronization server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
