# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Anki synchronization server systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ anki_identifier }}.service"
  register: anki_service_stat

- name: Uninstall Anki synchronization server systemd services and files
  when: anki_service_stat.stat.exists | bool
  block:
    - name: Ensure Anki synchronization server systemd service is stopped
      ansible.builtin.service:
        name: "{{ anki_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Anki synchronization server systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ anki_identifier }}.service"
        state: absent

    - name: Ensure Anki synchronization server support files do not exist
      ansible.builtin.file:
        path: "{{ anki_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Anki synchronization server image source files path does not exist
      ansible.builtin.file:
        path: "{{ anki_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Anki synchronization server container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ anki_container_network }}"
        state: absent

    - name: Ensure Anki synchronization server container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ anki_container_network }}
      register: network_deletion_result
      changed_when: anki_container_network in network_deletion_result.stdout

- name: Check existence of Anki synchronization server local data path
  ansible.builtin.stat:
    path: "{{ anki_data_path }}"
  register: anki_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Anki synchronization server local data remains
  when: anki_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Anki synchronization server instance has been removed, some old data remains in `{{ anki_data_path }}`. Feel free to delete it."
        ]
      }}
